[hls]
relative_roots=/home/albasg/Documentos/semestre-2/pd/project/GPU4S_Bench/gpu4s_benchmark/fast_fourier_transform_window_bench/cpu_functions
# Inferred from syn.array_partition.complete_threshold=4
syn.directive.array_partition=hotbm_::sin_or_cos<double>/out_bits.i dim=1 type=complete variable=out_bits.i
syn.directive.array_partition=hotbm_::sin_or_cos<double>/c.i dim=1 type=complete variable=c.i
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=hotbm_::sin_or_cos<double>/anonymous 
syn.directive.pipeline=aux_fft_function/VITIS_LOOP_21_2 
syn.directive.pipeline=aux_fft_function/VITIS_LOOP_40_5 
syn.directive.pipeline=hotbm_::sin_or_cos<double>/anonymous 
syn.directive.pipeline=hotbm_::sin_or_cos<double>/anonymous 
syn.directive.pipeline=hotbm_::sin_or_cos<double>/anonymous 
syn.directive.pipeline=fft_function/VITIS_LOOP_71_2 


