[hls]
relative_roots=/home/albasg/Documentos/semestre-2/pd/project/GPU4S_Bench/gpu4s_benchmark/matrix_multiplication_bench_fp16/cpu
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=matrix_multiplication/VITIS_LOOP_8_3 


