[hls]
relative_roots=/home/albasg/Documentos/semestre-2/pd/project/GPU4S_Bench/gpu4s_benchmark/softmax_bench/cpu_functions
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=softmax/VITIS_LOOP_48_2 
syn.directive.pipeline=softmax/VITIS_LOOP_58_4 
# Inferred from Performance Budgeter performance directives
syn.directive.loop_flatten=softmax/VITIS_LOOP_56_3  


