[hls]
relative_roots=/home/albasg/Documentos/semestre-2/pd/project/GPU4S_Bench/gpu4s_benchmark/fast_fourier_transform_2D_bench/cpu_functions
# Inferred from syn.array_partition.complete_threshold=4
syn.directive.array_partition=hotbm_::sin_or_cos<float>/out_bits.i dim=1 type=complete variable=out_bits.i
syn.directive.array_partition=hotbm_::sin_or_cos<float>/c.i dim=1 type=complete variable=c.i
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=hotbm_::sin_or_cos<float>/anonymous 
syn.directive.pipeline=fft2d_flat/VITIS_LOOP_59_1 
syn.directive.pipeline=fft2d_flat/VITIS_LOOP_37_5 
syn.directive.pipeline=hotbm_::sin_or_cos<float>/anonymous 
syn.directive.pipeline=hotbm_::sin_or_cos<float>/anonymous 
syn.directive.pipeline=fft2d_flat/VITIS_LOOP_21_2 
syn.directive.pipeline=fft2d_flat/VITIS_LOOP_72_5 
syn.directive.pipeline=fft2d_flat/VITIS_LOOP_69_4 


