[hls]
relative_roots=/home/albasg/Documentos/semestre-2/pd/project/GPU4S_Bench/gpu4s_benchmark/relu_bench/cpu_functions
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=relu/VITIS_LOOP_21_2 
# Inferred from Performance Budgeter performance directives
syn.directive.loop_flatten=relu/VITIS_LOOP_19_1  


